#!/usr/bin/env bash
#
# End-to-end check of the Autoconf tools: every installed program runs, and the
# `configure` script autoconf generates is itself runnable and produces the
# outputs it promised.
#
# The sample package deliberately avoids `AC_PROG_CC` so that running the
# generated `configure` does not need a compiler on the test machine.

set -euo pipefail

# --- begin runfiles.bash initialization v3 ---
# Copy-pasted from the Bazel Bash runfiles library v3.
set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
# shellcheck disable=SC1090
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null ||
  source "$0.runfiles/$f" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "$0.runfiles/MANIFEST" | cut -f2- -d' ')" 2>/dev/null ||
  source "$(grep -sm1 "^$f " "$0.exe.runfiles/MANIFEST" | cut -f2- -d' ')" 2>/dev/null ||
  { echo >&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
# --- end runfiles.bash initialization v3 ---

AUTOCONF="$(rlocation "${AUTOCONF_RLOCATIONPATH}")"
AUTOHEADER="$(rlocation "${AUTOHEADER_RLOCATIONPATH}")"
AUTOM4TE="$(rlocation "${AUTOM4TE_RLOCATIONPATH}")"
AUTORECONF="$(rlocation "${AUTORECONF_RLOCATIONPATH}")"
AUTOSCAN="$(rlocation "${AUTOSCAN_RLOCATIONPATH}")"
AUTOUPDATE="$(rlocation "${AUTOUPDATE_RLOCATIONPATH}")"
IFNAMES="$(rlocation "${IFNAMES_RLOCATIONPATH}")"

readonly EXPECTED_VERSION="2.73"

fail() {
  echo >&2 "FAIL: $*"
  exit 1
}

# Every tool reports the same Autoconf version.
for tool in "${AUTOCONF}" "${AUTOHEADER}" "${AUTOM4TE}" "${AUTORECONF}" \
            "${AUTOSCAN}" "${AUTOUPDATE}" "${IFNAMES}"; do
  version="$("${tool}" --version)" ||
    fail "${tool} --version exited non-zero"
  case "${version}" in
    *"GNU Autoconf) ${EXPECTED_VERSION}"*) ;;
    *) fail "${tool} --version reported '$(echo "${version}" | head -n1)', want ${EXPECTED_VERSION}" ;;
  esac
done

workdir="${TEST_TMPDIR:-$(mktemp -d)}/pkg"
mkdir -p "${workdir}"
cd "${workdir}"

cat > configure.ac <<'EOF'
AC_INIT([smoke], [1.0], [nobody@example.com])
AC_CONFIG_HEADERS([config.h])
AC_CONFIG_FILES([report])
AC_DEFINE([SMOKE_TEST], [1], [Defined when built by the Bazel smoke test.])
AC_SUBST([GREETING], [hello])
AC_OUTPUT
EOF

cat > report.in <<'EOF'
greeting=@GREETING@
package=@PACKAGE_NAME@
EOF

cat > smoke.c <<'EOF'
#include <stdio.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
int main(void) { return printf("%d\n", SMOKE_TEST) < 0; }
EOF

# --- autoconf ---------------------------------------------------------------
"${AUTOCONF}" || fail "autoconf exited non-zero"
[[ -f configure ]] || fail "autoconf did not write configure"
grep -q 'Generated by GNU Autoconf 2.73' configure ||
  fail "configure is missing the Autoconf 2.73 banner"

# --- autoheader -------------------------------------------------------------
"${AUTOHEADER}" || fail "autoheader exited non-zero"
grep -q '#undef SMOKE_TEST' config.h.in ||
  fail "config.h.in does not declare SMOKE_TEST"

# --- the generated configure actually runs ----------------------------------
chmod +x configure
./configure > configure.log 2>&1 ||
  { cat configure.log >&2; fail "generated configure exited non-zero"; }
grep -q '#define SMOKE_TEST 1' config.h ||
  fail "configure did not define SMOKE_TEST in config.h"
grep -q '^greeting=hello$' report ||
  fail "configure did not substitute @GREETING@"
grep -q '^package=smoke$' report ||
  fail "configure did not substitute @PACKAGE_NAME@"

# --- autoreconf -------------------------------------------------------------
# Regenerating in place must be a no-op-equivalent, not an error. This is the
# path that resolves sibling tools through the `%C` table in `autoreconf`.
rm -f configure config.h.in
"${AUTORECONF}" --force > autoreconf.log 2>&1 ||
  { cat autoreconf.log >&2; fail "autoreconf --force exited non-zero"; }
[[ -f configure ]] || fail "autoreconf did not regenerate configure"
[[ -f config.h.in ]] || fail "autoreconf did not regenerate config.h.in"

# --- autoscan ---------------------------------------------------------------
# Exercises lib/autoscan/autoscan.list, which is generated at build time.
scandir="${workdir}/scan"
mkdir -p "${scandir}"
cp smoke.c "${scandir}/"
(cd "${scandir}" && "${AUTOSCAN}") || fail "autoscan exited non-zero"
grep -q 'AC_PREREQ' "${scandir}/configure.scan" ||
  fail "configure.scan is missing AC_PREREQ"
grep -q 'AC_CHECK_HEADERS' "${scandir}/configure.scan" ||
  fail "autoscan did not notice unistd.h; autoscan.list is probably empty"

# --- autoupdate -------------------------------------------------------------
updir="${workdir}/update"
mkdir -p "${updir}"
cat > "${updir}/configure.ac" <<'EOF'
AC_INIT([old], [1.0])
AC_HAVE_HEADERS([stdio.h])
AC_OUTPUT
EOF
(cd "${updir}" && "${AUTOUPDATE}") || fail "autoupdate exited non-zero"
grep -q 'AC_CHECK_HEADERS' "${updir}/configure.ac" ||
  fail "autoupdate did not modernize AC_HAVE_HEADERS"

# --- ifnames ----------------------------------------------------------------
names="$("${IFNAMES}" smoke.c)" || fail "ifnames exited non-zero"
case "${names}" in
  *HAVE_UNISTD_H*) ;;
  *) fail "ifnames did not report HAVE_UNISTD_H, got: ${names}" ;;
esac

# --- autom4te ---------------------------------------------------------------
# Tracing is how automake, aclocal and friends consume Autoconf, so it gets its
# own check rather than riding along on the autoconf run above.
trace="$("${AUTOM4TE}" --cache '' --language autoconf --trace 'AC_INIT:$1' configure.ac)" ||
  fail "autom4te --trace exited non-zero"
[[ "${trace}" == "smoke" ]] ||
  fail "autom4te --trace AC_INIT reported '${trace}', want 'smoke'"

# --- environment overrides --------------------------------------------------
# The whole point of the relocatability patch is that an action can repoint any
# tool the scripts shell out to. Checked negatively: if the override were
# ignored, the run would succeed against the runfiles copy instead of failing.
assert_override_is_honored() {
  local var="$1" tool="$2"
  shift 2
  if env "${var}=/nonexistent/definitely-not-a-program" "${tool}" "$@" \
       > override.log 2>&1; then
    cat override.log >&2
    fail "${var} was ignored: ${tool} succeeded with ${var} pointing at nothing"
  fi
}

assert_override_is_honored M4 "${AUTOCONF}"
assert_override_is_honored AUTOM4TE "${AUTOCONF}"
assert_override_is_honored AUTOM4TE "${AUTOHEADER}"
# AC_MACRODIR is upstream's override for autoscan's and autoupdate's macro
# search path; the patch is what makes autoscan honor it.
assert_override_is_honored AC_MACRODIR "${AUTOSCAN}"

echo "PASS"
