"FFmpeg component dependency resolver mirroring configure check_deps."

def resolve_components(enabled_components, component_registry, extra_registry, available_libs = []):
    """Resolve component dependencies returning the full set of enabled flags.

    Args:
      enabled_components: List of component names initially enabled.
      component_registry: Dict mapping component name to its dependency metadata.
      extra_registry: Dict mapping CONFIG_EXTRA subsystem name to its dependency metadata.
      available_libs: List of library names that are unconditionally available
          (e.g. "zlib", "bzlib"). These satisfy dep checks but are not emitted
          in generated headers.

    Returns:
      Dict mapping every component/subsystem name to a bool indicating whether
      it is enabled after dependency resolution.
    """
    state = {}
    for comp in component_registry:
        state[comp] = False
    for comp in extra_registry:
        state[comp] = False
    for lib in available_libs:
        state[lib] = True
    for comp in enabled_components:
        if comp in state:
            state[comp] = True

    changed = True
    iteration = 0

    for _round in range(50):
        if not changed:
            break
        changed = False
        iteration = iteration + 1

        for comp in state.keys():
            if not state[comp]:
                continue
            entry = _get_entry(comp, component_registry, extra_registry)
            for sel in entry.get("select", []):
                if sel in state and not state[sel]:
                    state[sel] = True
                    changed = True
            for sug in entry.get("suggest", []):
                if sug in state and not state[sug]:
                    state[sug] = True
                    changed = True

        for comp in state.keys():
            if not state[comp]:
                continue
            entry = _get_entry(comp, component_registry, extra_registry)

            deps = entry.get("deps", [])
            if deps and not _all_enabled(deps, state):
                state[comp] = False
                changed = True
                continue

            deps_any = entry.get("deps_any", [])
            if deps_any and not _any_enabled(deps_any, state):
                state[comp] = False
                changed = True
                continue

            conflicts = entry.get("conflict", [])
            if conflicts and _any_enabled(conflicts, state):
                state[comp] = False
                changed = True
                continue

            selects = entry.get("select", [])
            if selects and not _all_enabled(selects, state):
                state[comp] = False
                changed = True
                continue

    return state

def _get_entry(comp, component_registry, extra_registry):
    entry = component_registry.get(comp)
    if entry != None:
        return entry
    entry = extra_registry.get(comp)
    if entry != None:
        return entry
    return {}

def _all_enabled(deps, state):
    for dep in deps:
        if dep not in state:
            return False
        if not state[dep]:
            return False
    return True

def _any_enabled(deps, state):
    for dep in deps:
        if dep in state and state[dep]:
            return True
    return False

def generate_config_components_lines(state, component_registry):
    """Generate config_components.h content (ALL_COMPONENTS only, no CONFIG_EXTRA).

    Args:
      state: Dict mapping component name to enabled bool, as returned by
          resolve_components.
      component_registry: Dict of component names whose keys determine which
          #define lines to emit.

    Returns:
      List of strings forming a complete config_components.h file.
    """
    lines = [
        "/* Automatically generated by Bazel - do not modify! */",
        "#ifndef FFMPEG_CONFIG_COMPONENTS_H",
        "#define FFMPEG_CONFIG_COMPONENTS_H",
    ]
    for comp in sorted(component_registry.keys()):
        if state.get(comp, False):
            val = "1"
        else:
            val = "0"
        lines.append("#define CONFIG_{} {}".format(comp.upper(), val))
    lines.append("#endif /* FFMPEG_CONFIG_COMPONENTS_H */")
    return lines

def generate_config_extra_lines(state, extra_registry):
    """Generate config_extra.h content (CONFIG_EXTRA subsystems only).

    Args:
      state: Dict mapping component name to enabled bool, as returned by
          resolve_components.
      extra_registry: Dict of CONFIG_EXTRA subsystem names whose keys determine
          which #define lines to emit.

    Returns:
      List of strings forming the config_extra.h snippet.
    """
    lines = [
        "/* Automatically generated by Bazel - do not modify! */",
        "/* CONFIG_EXTRA subsystems resolved from component dependencies */",
    ]
    for comp in sorted(extra_registry.keys()):
        if state.get(comp, False):
            val = "1"
        else:
            val = "0"
        lines.append("#define CONFIG_{} {}".format(comp.upper(), val))
    return lines
