"""geninit.sh as a Starlark function.

Makefile.am:50 and :64 run `sh geninit.sh $(cat libgrub_a_init.lst)` to
write the `grub_init_all`/`grub_fini_all` pair that calls every module's
GRUB_MOD_INIT/GRUB_MOD_FINI; the list of modules is fixed by the source list,
so the BUILD file passes it in directly.
"""

visibility("private")

def geninit(modules):
    """Returns the lines of geninit.sh's output for `modules`."""
    return [
        "/* This file is automatically generated by geninit.sh. DO NOT EDIT! */",
        "",
        "#include <grub/emu/misc.h>",
        "",
    ] + [
        line
        for m in modules
        for line in [
            "extern void grub_{}_init (void);".format(m),
            "extern void grub_{}_fini (void);".format(m),
        ]
    ] + [
        "",
        "void",
        "grub_init_all (void)",
        "{",
    ] + ["grub_{}_init ();".format(m) for m in modules] + [
        "}",
        "",
        "void",
        "grub_fini_all (void)",
        "{",
    ] + ["grub_{}_fini ();".format(m) for m in modules] + [
        "}",
    ]
